### PR TITLE
Add create token parameters into body request

### PR DESCRIPTION
**Pull request by eusonlito**
POST and PUT request must add parameters into request body and not into GET QUERY string. Related #16

### CODE REVIEW

**Comment by eusonlito** [comment]
I have updated code style to PSR-2 and added a more detailed error response :)

Regards!

**Comment by tomloprod** [comment]
@eusonlito Wow, amazing! Graciñas :-)

**Comment by eusonlito** [comment]
Remember to add a new release ;)

**Comment by tomloprod** [comment]
@eusonlito Ooops! Right, thanks for remember me that :-)

**Pull request merged**
