### PR TITLE
New version 1.0.3

### PR DESCRIPTION
**Pull request by ramoncarreras**
- Added listTokens() method.
- Fix incorrect PHPDoc
- Updated README.md
- Change version to 1.0.3

### CODE REVIEW

**Comment by tomloprod** [comment]
Thank you for your contribute. :-)

**Comment by ramoncarreras** [comment]
I don't know how to update release version svg image of README.md.

Can you update it to 1.0.3 or explain me how to do it?

**Comment by tomloprod** [comment]
@ramoncarreras  It's an automatic process: the version is automatically extracted from the last released version. Now it's 1.0.3.

**Comment by ramoncarreras** [comment]
mmm.. OK. Understood. Thanks @tomloprod!

**Pull request merged**
